apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-cm
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: {{ .Values.server.name }}
data:
{{- toYaml .Values.server.config | nindent 4 }}
{{- if .Values.ssoAuth.enabled }}
    oidc.config: |
      name: {{ .Values.ssoAuth.name }}
      issuer: {{ .Values.ssoAuth.issuer }}
      clientID: {{ .Values.ssoAuth.clientId }}
      clientSecret: {{ .Values.ssoAuth.clientSecret }}
      requestedScopes:
      {{- range .Values.ssoAuth.requestedScopes }}
        {{ print "- " (. | quote) }}
      {{- end }}
      requestedIDTokenClaims:
      {{- toYaml .Values.ssoAuth.requestedIDTokenClaims | nindent 7 }}
{{- end }}
