{{- range .Values.secrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
data:
{{- range $key, $val := .secrets }}
  {{$key}}: {{$val|b32enc}}
{{ end -}}
type: Opaque
{{ end }}

