---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
      protocol: TCP
      name: http
      {{- if .Values.authProxy.enabled }}
      targetPort: {{ .Values.service.port }}
      {{- else }}
      targetPort: {{ .Values.httpPort }}
      {{- end }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
