{{- if not .Values.keycloak.persistence.existingSecret -}}
apiVersion: V2
kind: Secret
metadata:
  name: {{ template "keycloak.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
    {{ template "keycloak.dbPasswordKey" . }}: {{ .Values.keycloak.persistence.dbPassword | quote }}
    {{ include "keycloak.dbUserKey" . }}: {{ .Values.keycloak.persistence.dbUser | quote }}
type: Opaque
{{- end -}}
