{{- if not .Values.keycloak.persistence.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keycloak.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
    {{ template "keycloak.dbPasswordKey" . }}: {{ toString .Values.secrets.keycloak.persistence.dbPassword | b64enc }}
    {{ include "keycloak.dbUserKey" . }}: {{ toString .Values.secrets.keycloak.persistence.dbUser | b64enc }}
type: Opaque
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keycloak.fullname" . }}-postgresql
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  password: {{ toString .Values.secrets.keycloak.persistence.dbPassword | b64enc }}