{{- $ingress := .Values.keycloak.ingress -}}
{{- if $ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.keycloak.service.name }}"
  namespace: {{ .Values.keycloak.ingress.namespace }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    kubernetes.io/ingress.class: merge
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.keycloak.service.hostname }}
  labels:
    {{- include "keycloak.commonLabels" . | nindent 4 }}
    {{- with $ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
{{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.keycloak.service.hostname | quote }}
      http:
        paths:
        {{- range .Values.keycloak.ingress.paths }}
          - path: {{ default "/*" .path }}
            backend:
              serviceName: {{ .serviceName }}
              servicePort: {{ .servicePort }}
  {{- end }}
{{- end -}}
