proxyinjector:
  replicas: 1
  mount: "configmap"

  #Add this if there's a Secret already deployed
  existingSecret: "" 

  # SealedSecret config
  configSealedSecret: 
  # SealedSecret data for CLIENT-ID and CLIENT-SECRET, each item is the namespace in which to create the secret.
  clientSealedSecrets:

  tolerations: {}
  labels:
    provider: stakater
    group: com.stakater.platform
    version: 0.0.2
  image:
    name: moveax/proxyinjector
    tag: "latest"
    pullPolicy: IfNotPresent

  data:
    config.yml: |-
      proxyconfig:
        gatekeeper-image: "moveax/keycloak-gatekeeper:latest" 
        enable-default-deny: true
        secure-cookie: true
        verbose: true
        enable-logging: true
        cors-origins:
          - '*'
        cors-methods:
        - GET
        - POST
        resources:
        - uri: '/*'


  # Set to false if you want to only watch its own namespace 
  watchGlobally: true 
  configFilePath: /etc/ProxyInjector
  
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi  