apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cole-alerts.fullname" . }}
  labels:
    {{- include "cole-alerts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cole-alerts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cole-alerts.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cole-alerts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SENDER_TYPE
            value: "slack"
          - name: INTERVAL
            value: "{{ .Values.configs.interval }}"
          - name: HTTP_ENDPOINT
            value: "{{ .Values.configs.slackHook }}"
          - name: SLACK_CHANNEL
            value: "{{ .Values.configs.slackChannel }}"
          - name: SLACK_USERNAME
            value: "{{ .Values.configs.slackUsername | default "Cole - DeadManSwitch Monitor" }}"
          - name: SLACK_ICON
            value: "{{ .Values.configs.slackIcon | default ":monkey_face:" }}"
          livenessProbe:
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
