{{- if eq .Values.database.type "postgresql" -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: sonar-postgres-sealed-secret
  namespace: sonar
spec:
  encryptedData:
    postgres-password:  {{ .Values.postgresPassword }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: sonar-postgres-sealed-secret
      namespace: sonar
    type: Opaque
status: {}  
{{- end -}}

