{{- if eq .Values.database.type "postgresql" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonarqube.name" . }}-postgres-secret
type: Opaque
data:
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc }}  
{{- end -}}