apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql.name" . }}
  labels:
    app: {{ include "postgresql.name" . }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgresql.name" . }}
      release: {{ .Release.Name | quote }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "postgresql.name" . }}
        release: {{ .Release.Name | quote }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: postgres  
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args: 
        {{- toYaml .Values.args | nindent 10 }}
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                  name:  {{ include "postgresql.name" . }}-data
                  key: POSTGRES_USER 
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                  name:  {{ include "postgresql.name" . }}-data
                  key: POSTGRES_PASSWORD 
        envFrom:
          - configMapRef:
              name: {{ include "postgresql.name" . }}-data
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: {{ include "postgresql.name" . }}-data
            subPath: postgres
      restartPolicy: Always
      volumes:
        - name: {{ include "postgresql.name" . }}-data
          persistentVolumeClaim:
            claimName: {{ include "postgresql.name" . }}-data
