apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    app: {{ include "postgresql.fullname" . }}
    release: {{ .Release.Name | quote }}
data:
  ALLOW_IP_RANGE: "0.0.0.0/0"
