apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
      annotations:
        sidecar.istio.io/inject: "false"
        
    spec:
      containers:
      - name: postgres  
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args: 
          - -c 
          - 'max_connections=300'
          - '-c'
          - 'max_wal_senders=50'
          - '-c'
          - 'max_replication_slots=50'
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                  name:  postgres-db
                  key: POSTGRES_USER 
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                  name:  postgres-db
                  key: POSTGRES_PASSWORD 
        envFrom:
          - configMapRef:
              name: postgres-configmap 
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-data
        
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data