apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: {{ include "postgresql.fullname" . }}
    release: {{ .Release.Name | quote }}
  name: {{ include "postgresql.fullname" . }}-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
