apiVersion: v1
kind: Secret
metadata:
  name: postgres-db
data:
   POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc }}
   POSTGRES_USER: {{ .Values.secrets.postgresUser | b64enc }}
type: Opaque