apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-viz.fullname" . }}
  labels:
{{ include "kafka-viz.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kafka-viz.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "kafka-viz.fullname" . }}
        app.kubernetes.io/name: {{ include "kafka-viz.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
      {{- range $key, $value := .Values.extraTemplateAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{ end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
          {{- range $i, $val := .Values.image.args }}
            - {{$val | quote}}
          {{ end -}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ include "kafka-viz.fullname" . }}
              containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}