{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.ingress.namespace }}
  name: "{{ .Values.service.name }}"
  labels:
    app: {{ template "kafka-viz.name" . }}
    chart: {{ template "kafka-viz.chart" .  }}
    release: "{{ .Release.Name }}"
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: '{{ $value }}'
    {{- end }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    kubernetes.io/ingress.class: merge
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.hostname }}
spec:
  rules:
    - host: {{ .Values.service.hostname | quote }}
      http:
        paths:
        {{- range .Values.ingress.paths }}
          - path: {{ default "/*" .path }}
            backend:
              serviceName: {{ .serviceName }}
              servicePort: {{ .servicePort }}
          {{- end }}
    {{- end }}