{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kafka-viz.serviceAccountName" . }}
  labels:
{{ include "kafka-viz.labels" . | indent 4 }}
{{- end -}}
