---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovh-lb-controller.fullname" . }}-secret
  namespace: {{ .Release.namespace }}
data:
  clouds.yml: |-
    {{ .Values.secrets.openstack.configb64 }}