{{- if and (eq .Values.proxyinjector.mount "secret") ( .Values.proxyinjector.configSealedSecret ) }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "proxyinjector-vol-config-name" . }}
  namespace: proxy-injector
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    config.yml: {{ .Values.proxyinjector.configSealedSecret | trim }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
{{- end }}